### ISSUE TITLE
Intro Bootstrap

### ISSUE THREAD

**Issue by tkwanjp** [tkwanjp/money-log#11]
As a replacement to Flat UI, I have decided to implement Flat UI looks hopefully with bootstrap considering a speed, easy-to-introduce as a top priority.

### この手順を使った:
https://qiita.com/kazutosato/items/d47b7705ee545de4cb1a#assets%E3%81%AB%E5%85%A5%E3%82%8C%E3%82%8B%E5%A0%B4%E5%90%88

ただし以下の部分的な変更は加えた

```
config/environment.production.rb
# config.assets.js_compressor=`は使わずに。
```

gem 'uflifier' は結局ES6には使えないことが判明して、使わないことにした。deleteすべきなんだけど、Gemfileから消してbundle install(docker comose build経由で) してもGemfile.lockにそれが反映されず、Herokuのビルド bundle install が実行されないので、

ひとまず
```
Gemfile
 gem 'uglifier' のままにした
```

```
本来は、
gem 'uglifier' # -> gem 'terser' にして
```
```
config.assets.js_compressor= :terser # にするのがベター。
```

Gemfile.lockが更新されない問題が解消されない限り、手を付けられない。
というかこの問題は、ほかのどのIssueをやるときにも、Gemfileを触るたびに、ぶつかる可能性がある。さっさと解決しておかないと、他の何も進まなくなる可能性はある。

**Comment by tkwanjp** [comment]
https://qiita.com/kazutosato/items/d47b7705ee545de4cb1a

この手順でいこうかな、とここにある２つのうちの１つで。

**Comment by tkwanjp** [comment]
https://qiita.com/sagawashu/items/6066ec3b758147687bd1

この手順は簡単そうに見えて、一度踏んでみて、途中でこけた。環境が微妙に違った。Railsの環境合わせておかないといけなかったな、と
当然のような教訓。

それにしても、ここに来て、Railsのこれ系にめちゃ惑わされている。

**Comment by tkwanjp** [comment]
これをフォローしてみる。

[assetsに入れる場合](https://qiita.com/kazutosato/items/d47b7705ee545de4cb1a#assets%E3%81%AB%E5%85%A5%E3%82%8C%E3%82%8B%E5%A0%B4%E5%90%88)

**Comment by tkwanjp** [comment]
手順踏んだ。localhost:3000すると、エラー
```
Error: File to import not found or unreadable: bootstrap.
        on line 17:1 of app/assets/stylesheets/application.scss
>> @import "bootstrap";

```
app/assets/stylesheets/application.scss
@import “bootstrap”; 
これ見つからないって。だよね、おれもこれどうやって探すんだろう、って思ったのよ。

gemはインストールされた？
-> gemはuglifier以外はインストールされているぽい。
```
$ gem list  
=> 
jquery-rails (4.5.1)
bootstrap (5.2.3)
popper_js (2.11.7)
uglifier　入ってない。
```

あ、たぶん docker compose up -d しなおしてないから、前のビルドで実行していて、だからないんだわbootstrap。

docker compose up -d しなおす！

違うエラーに変わった。

```
Sprockets::Rails::Helper::AssetNotPrecompiledError in Expenses#new
/myapp/app/views/layouts/application.html.erb
　<%= javascript_include_tag ‘application’, ‘data-turbolinks-track’: ‘reload’ %>
raised:
Asset `application.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link application.js

and restart your server
```

`  //= link application.js`加えると、たしかに動作する。
でも、
app/assets/config/manifest.js
```
//= link_tree ../images
//= lind_directory ../javascripts .js
//= link_directory ../stylesheets .css
```
これで書けているはずなんだけどなー。。
app/assets -
		    |- config/manifest.js
		    |- javascript.application.js

タイポ！ ‘lind’! -> ‘link’
`//= lind_directory ../javascripts .js`

予測補完を効かせてないから、こういうミス発生するんだよな〜。
- [ ] 使ってるエディターの設定するか、エディターを替えないとな
- [ ] ターミナルでも効かせるようにしないとな。

**Comment by tkwanjp** [comment]
ここでエラー起こる心配残るな

config/environment/production.rb
  # Compress Javascirpt using a preprocessor.
  config.assets.js_compressor = :uglifier

**Comment by tkwanjp** [comment]
やはり、productionのビルド通らなかった。

git push heroku
=>
```
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !

```

**Comment by tkwanjp** [comment]
localで gem 'uglifier' installedできた。
git push herokuすると同様のエラー。どうやらproduction.rbでの書き方が改訂されているらしい。

```
...
 rake aborted!
remote:        Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
remote:        --
remote:         10920 (function (global, factory) {
remote:         10921   typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('@popperjs/core')) :
remote:         10922   typeof define === 'function' && define.amd ? define(['@popperjs/core'], factory) :
remote:         10923   (global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.bootstrap = factory(global.Popper));
remote:         10924 })(this, (function (Popper) { 'use strict';
remote:         10925 
remote:         10926   function _interopNamespace(e) {
remote:         10927     if (e && e.__esModule) return e;
remote:            =>     const n = Object.create(null, { [Symbol.toStringTag]: { value: 'Module' } });
remote:         10929     if (e) {
remote:         10930       for (const k in e) {
remote:         10931         if (k !== 'default') {
remote:         10932           const d = Object.getOwnPropertyDescriptor(e, k);
remote:         10933           Object.defineProperty(n, k, d.get ? d : {
remote:         10934             enumerable: true,
remote:         10935             get: () => e[k]
remote:         10936           });
remote:        ==
remote:        /tmp/build_9082f0e0/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
remote:        /tmp/build_9082f0e0/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
remote:        /tmp/build_9082f0e0/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:176:in `compile_with_map'
remote:        /tmp/build_9082f0e0/vendor/bundle/ruby/2.7.0/gems/sprockets-4.2.0/lib/sprockets/uglifier_compressor.rb:58:in `call'
remote:        /tmp/build_9082f0e0/vendor/bundle/ruby/2.7.0/gems/sprockets-4.2.0/lib/sprockets/uglifier_compressor.rb:30:in `call'
...
```

**Comment by tkwanjp** [comment]
config/environment/production.rb

`  config.assets.js_compressor = :uglifier
`->
  `config.assets.js_compressor = Uglifier.new(harmony: true)`
に書き換える。

またエラーがちょっと変わった。もうどうしていいかわからない。

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        /tmp/build_66c12381/vendor/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
remote:        /tmp/build_66c12381/vendor/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
remote:        /tmp/build_66c12381/vendor/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
remote:        yarn install v1.22.19
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        Done in 27.20s.
remote:        rake aborted!
remote:        Uglifier::Error: 
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
remote:        /tmp/build_66c12381/vendor/bundle/ruby/2.7.0/gems/sprockets-4.2.0/lib/sprockets/compressing.rb:84:in `block in js_compressor='

```

**Comment by tkwanjp** [comment]
> UglifyJS only works with ES5. If you need to compress ES6, [ruby-terser](https://github.com/ahorek/terser-ruby) is a better option.

こういうことみたい。
uflifier をなんとか使う迂回路もあるみたいだけど、もういいや。

**Comment by tkwanjp** [comment]
Deleted `uglifier` gem, and disabled `config.assets.js_compressor =`.

```
$ rake assets:precompile
=> [1/4] Resolving packages...
success Already up-to-date.
```

**Comment by tkwanjp** [comment]
Gemfile.lockが更新されなくて、herokuのビルド通らない。

https://freiheitp.hatenablog.com/entry/2019/11/12/223733
docker compose build　では bundle install されるけど、Gemfile.lockは更新されない。rails s すると更新される
みたいに書かれてるけど、docker compose up -d した時点で、rails sされてるし、
あえてrails sしなおしたけど、
```
A server is already running. Check /myapp/tmp/pids/server.pid.
Exiting
```
だって。

**Comment by tkwanjp** [comment]
なんとなく想像する原因は、get branch 現在地が、ずれてるんじゃないか？
docker compose build しているところと、git pushしているところの間で。

**Comment by tkwanjp** [comment]
Docker compose build --no-cache しても結果は変わらず。

**Comment by tkwanjp** [comment]
諦めて、

Gemfile
`gem 'uglifier'`

戻して、いったんこれでgit push heroku。

**Comment by tkwanjp** [comment]
2c305db1d7a87e67e2767dae8f8fe0feae82b8dc

**Comment by tkwanjp** [comment]
Gemfile.lockが更新されない問題についてはIssueを追加した:

https://github.com/tkwanjp/money-log/issues/16
